// This file is auto-generated by @hey-api/openapi-ts

export type Answer = {
    answer: string;
    documents: Array<Document>;
};

export type Body_upload_file_upload_file_post = {
    file: (Blob | File);
};

export type Book = {
    title: string;
    formats: {
        [key: string]: (string);
    };
};

export type Document = {
    content: string;
    position: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Question = {
    question: string;
    book: string;
    percentage?: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PostUploadFileData = {
    body: Body_upload_file_upload_file_post;
};

export type PostUploadFileResponse = (unknown);

export type PostUploadFileError = (HTTPValidationError);

export type PostImportBookData = {
    body: Book;
};

export type PostImportBookResponse = (unknown);

export type PostImportBookError = (HTTPValidationError);

export type GetCoverImageByFilenameData = {
    path: {
        filename: string;
    };
};

export type GetCoverImageByFilenameResponse = (unknown);

export type GetCoverImageByFilenameError = (HTTPValidationError);

export type PostAskQuestionData = {
    body: Question;
};

export type PostAskQuestionResponse = (Answer);

export type PostAskQuestionError = (HTTPValidationError);

export type GetChromaData = {
    body: Book;
};

export type GetChromaResponse = (unknown);

export type GetChromaError = (HTTPValidationError);

export type DeleteClearDbResponse = (unknown);

export type DeleteClearDbError = unknown;

export type GetBooksResponse = (Array<(string)>);

export type GetBooksError = unknown;

export type GetStatusResponse = (unknown);

export type GetStatusError = unknown;