// This file is auto-generated by @hey-api/openapi-ts

export type Answer = {
    answer: string;
    documents: Array<Document>;
};

export type Body_upload_file_upload_file_post = {
    file: (Blob | File);
};

export type BookFormats = {
    'application/epub+zip': string;
    'image/jpeg': string;
};

export type BookMetadata = {
    title: string;
    uuid: string;
    authors: string;
    translators: string;
    languages: string;
    cover_url?: string;
};

export type Document = {
    content: string;
    position: string;
};

export type GutenbergBook = {
    title: string;
    id: number;
    formats: BookFormats;
    authors?: Array<Person>;
    translators?: Array<Person>;
    languages?: Array<(string)>;
    subjects?: Array<(string)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Person = {
    name: string;
    birth_year?: (number | null);
    death_year?: (number | null);
};

export type Question = {
    question: string;
    book: string;
    percentage?: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PostUploadFileData = {
    body: Body_upload_file_upload_file_post;
};

export type PostUploadFileResponse = (unknown);

export type PostUploadFileError = (HTTPValidationError);

export type PostImportBookData = {
    body: GutenbergBook;
};

export type PostImportBookResponse = (unknown);

export type PostImportBookError = (HTTPValidationError);

export type PostAskQuestionData = {
    body: Question;
};

export type PostAskQuestionResponse = (Answer);

export type PostAskQuestionError = (HTTPValidationError);

export type GetChromaData = {
    body: BookMetadata;
};

export type GetChromaResponse = (unknown);

export type GetChromaError = (HTTPValidationError);

export type DeleteClearDbResponse = (unknown);

export type DeleteClearDbError = unknown;

export type GetBooksResponse = (Array<BookMetadata>);

export type GetBooksError = unknown;

export type GetStatusResponse = (unknown);

export type GetStatusError = unknown;